import 'dart:ui';

import 'package:auto_route/auto_route.dart';
import 'package:book_ai/domain/api_input/i_api_input_repository.dart';
import 'package:book_ai/domain/book/book.dart';
import 'package:book_ai/domain/story/story.dart';
import 'package:book_ai/infrastructure/book/book_repository.dart';
import 'package:book_ai/infrastructure/story/story_dtos.dart';
import 'package:book_ai/infrastructure/story/story_repository.dart';
import 'package:book_ai/presentation/reusable_components/cards/star_rating.dart';
import 'package:book_ai/presentation/routing/router/router.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';

class StoryHistoryItem extends StatelessWidget {
  final StoryItem story;
  final VoidCallback onDelete;
  const StoryHistoryItem(
      {super.key, required this.story, required this.onDelete});

  @override
  Widget build(BuildContext context) {
    return Container(
      margin: EdgeInsets.only(top: 13.w, bottom: 13.w),
      child: Dismissible(
        direction: DismissDirection.endToStart,
        background: Container(
          decoration: BoxDecoration(
              color: Theme.of(context).disabledColor,
              borderRadius: BorderRadius.circular(13.w)),
          alignment: Alignment.centerRight,
          padding: EdgeInsets.symmetric(horizontal: 30.w),
          child: Icon(
            Icons.delete,
            color: Theme.of(context).focusColor,
            size: 25.w,
          ),
        ),
        onDismissed: (_) async {
          onDelete();
        },
        key: UniqueKey(),
        child: GestureDetector(
          onTap: () {
            final storyDto = StoryDto.fromDomain(story);
            AutoRouter.of(context).push(
              StoryRoute(story: storyDto),
            );
            // Navigate to another page when the card is pressed
            // Navigator.push(
            //   context,
            //   MaterialPageRoute(
            //     builder: (context) => AnotherPage(),
            //   ),
            // );
          },
          child: Card(
            shape: RoundedRectangleBorder(
              borderRadius:
                  BorderRadius.circular(13.w), // Adjust the value as needed
            ),
            elevation: 0,
            color: Colors.transparent,
            margin: EdgeInsets.all(0),
            child: Row(
              children: [
                Stack(
                  alignment: Alignment.center,
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.circular(15.w),
                      child: BackdropFilter(
                        filter: ImageFilter.blur(sigmaX: 10, sigmaY: 10),
                        child: Container(
                          width: 100.w,
                          height: 100.w,
                          color: Theme.of(context).disabledColor,
                        ),
                      ),
                    ),
                    Text(
                      story.storyTitle.getOrCrash()[0],
                      style: Theme.of(context).textTheme.displayLarge,
                    ),
                  ],
                ),
                // Details section
                Flexible(
                  child: Padding(
                    padding: EdgeInsets.all(16.w),
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        // Heading with two lines
                        Text(
                          story.storyTitle.getOrCrash(),
                          style: Theme.of(context).textTheme.labelLarge,
                          overflow: TextOverflow.ellipsis,
                          maxLines: 2,
                        ),
                        // Subheading
                        Text(
                          'Generated by you',
                          style: Theme.of(context).textTheme.labelSmall,
                        ),
                      ],
                    ),
                  ),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
