import 'dart:ui';

import 'package:auto_route/annotations.dart';
import 'package:book_ai/infrastructure/story/story_dtos.dart';
import 'package:book_ai/presentation/reusable_components/backgrounds/animatied_background.dart';
import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:google_fonts/google_fonts.dart';

@RoutePage()
class StoryScreen extends StatefulWidget {
  StoryDto story;
  StoryScreen({super.key, required this.story});
  @override
  _StoryScreenState createState() => _StoryScreenState();
}

class _StoryScreenState extends State<StoryScreen> {
  double _fontSize = 15.w; // Initial font size

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      extendBody: true,
      extendBodyBehindAppBar: true,
      appBar: AppBar(
        toolbarHeight: 50.h,
        backgroundColor: Colors.transparent,
        elevation: 0,
        centerTitle: true,
        title: Column(
          children: [
            Text(
              widget.story.storyTitle,
              style: Theme.of(context).textTheme.headlineLarge,
            ),
            Text(
              'Generated by you',
              style: Theme.of(context).textTheme.labelSmall,
            )
          ],
        ),
        flexibleSpace: Container(
          decoration: const BoxDecoration(
            gradient: LinearGradient(
              begin: Alignment.topCenter,
              end: Alignment.bottomCenter,
              colors: [
                Colors.black,
                Colors.black,
                Colors.black,
                Color.fromARGB(209, 0, 0, 0),
                Color.fromARGB(175, 0, 0, 0),
                Colors.transparent
              ],
            ),
          ),
        ),
      ),
      body: Stack(
        children: [
          const AnimatedBackground(),
          SingleChildScrollView(
            scrollDirection: Axis.vertical,
            child: SafeArea(
              child: Container(
                margin: EdgeInsets.only(right: 20.w, left: 20.w),
                child: Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.center,
                  children: [
                    SizedBox(height: 20.h),
                    Text(widget.story.content,
                        style: GoogleFonts.quicksand(
                          textStyle: TextStyle(
                            color: Theme.of(context).primaryColor,
                            fontSize: _fontSize,
                            fontWeight: FontWeight.w400,
                          ),
                        )),
                  ],
                ),
              ),
            ),
          ),
        ],
      ),
      bottomNavigationBar: Container(
        decoration: BoxDecoration(
          image: const DecorationImage(
            image: AssetImage('assets/images/nav-bg.png'),
            fit: BoxFit.cover,
          ),
          borderRadius: BorderRadius.only(
            topLeft: Radius.circular(50.w),
            topRight: Radius.circular(50.w),
          ),
        ),
        child: ClipRRect(
          borderRadius: BorderRadius.only(
            topLeft: Radius.circular(50.w),
            topRight: Radius.circular(50.w),
          ),
          child: BackdropFilter(
            filter: ImageFilter.blur(
              sigmaX: 10,
              sigmaY: 10,
            ),
            blendMode: BlendMode.srcOver,
            child: Container(
              height: 65.h,
              color: Theme.of(context).disabledColor,
              child: Padding(
                padding: EdgeInsets.only(right: 20.w, left: 20.w),
                child: Column(
                  children: [
                    Align(
                      alignment: Alignment.bottomLeft,
                      child: Padding(
                        padding: EdgeInsets.only(left: 15.w, top: 10.h),
                        child: Text(
                          'Font Size',
                          style: Theme.of(context).textTheme.bodyMedium,
                        ),
                      ),
                    ),
                    SizedBox(
                      height: 25.h,
                      child: Slider(
                        activeColor: Theme.of(context).focusColor,
                        inactiveColor: Theme.of(context).primaryColor,
                        value: _fontSize,
                        min: 10.w,
                        max: 50.w,
                        onChanged: (value) {
                          setState(() {
                            _fontSize = value;
                          });
                        },
                      ),
                    ),
                  ],
                ),
              ),
            ),
          ),
        ),
      ),
    );
  }
}
