// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJ3Bzg0--QB8WYeLz9QxlhVJ66FvGdb8E',
    appId: '1:1085950234103:web:d8ea58567de73345d172f2',
    messagingSenderId: '1085950234103',
    projectId: 'taletuner-523af',
    authDomain: 'taletuner-523af.firebaseapp.com',
    storageBucket: 'taletuner-523af.appspot.com',
    measurementId: 'G-E69V3039RM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwRBiqeVZlhNMt4PuB4iHz2RWYqYBGHS4',
    appId: '1:1085950234103:android:c1a2660757b90612d172f2',
    messagingSenderId: '1085950234103',
    projectId: 'taletuner-523af',
    storageBucket: 'taletuner-523af.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWIDFhYbBdQt_0vO_ietKa5KlYstTJUaA',
    appId: '1:1085950234103:ios:0d3e1d7562622926d172f2',
    messagingSenderId: '1085950234103',
    projectId: 'taletuner-523af',
    storageBucket: 'taletuner-523af.appspot.com',
    iosClientId: '1085950234103-uhdpnia3ld835grjel4npiuhk6ru84sc.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWIDFhYbBdQt_0vO_ietKa5KlYstTJUaA',
    appId: '1:1085950234103:ios:0dde7e4dd19131c7d172f2',
    messagingSenderId: '1085950234103',
    projectId: 'taletuner-523af',
    storageBucket: 'taletuner-523af.appspot.com',
    iosClientId: '1085950234103-rhf2v9u3l51rjegih41upg9gtgat5v7j.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookAi.RunnerTests',
  );
}
